# Generated by Django 5.2.5 on 2025-08-20 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_plan_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.plan'),
        ),
    ]
