# Generated by Django 5.2.5 on 2025-08-21 23:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_reviewplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewplan',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
