# Generated by Django 5.2.5 on 2025-08-21 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_reviewplan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewplan',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_plans', to='users.studentprofile'),
        ),
    ]
