# Generated by Django 5.2.5 on 2025-08-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_reviewplan_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewplan',
            name='ayat_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewplan',
            name='surah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
