# Generated by Django 5.2.5 on 2025-08-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_reviewplan_ayat_count_reviewplan_surah'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewplan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
