# Generated by Django 5.2.5 on 2025-08-25 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_reviewplan_reminder_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewplan',
            name='successful_reviews_manual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.evaluation'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='commitment',
            field=models.FloatField(default=0),
        ),
    ]
