# Generated by Django 5.2.5 on 2025-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_studentprofile_last_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
