# Generated by Django 5.2.5 on 2025-08-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='custom_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Plan Code'),
        ),
    ]
