# Generated by Django 5.2.5 on 2025-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_plan_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='التقييم'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reviews',
            field=models.IntegerField(default=0, verbose_name='المراجعات الناجحة'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='commitment',
            field=models.FloatField(default=0, verbose_name='معدل الالتزام'),
        ),
    ]
