# Generated by Django 5.2.5 on 2025-08-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_studentprofile_country_studentprofile_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='level',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='monthly_level',
            field=models.CharField(blank=True, choices=[('ضعيف', 'ضعيف'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز'), ('ممتاز جدا', 'ممتاز جدا')], max_length=20, null=True, verbose_name='التقييم الشهري'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='weekly_level',
            field=models.CharField(blank=True, choices=[('ضعيف', 'ضعيف'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز'), ('ممتاز جدا', 'ممتاز جدا')], max_length=20, null=True, verbose_name='التقييم الأسبوعي'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='yearly_level',
            field=models.CharField(blank=True, choices=[('ضعيف', 'ضعيف'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز'), ('ممتاز جدا', 'ممتاز جدا')], max_length=20, null=True, verbose_name='التقييم السنوي'),
        ),
    ]
