# Generated by Django 5.2.5 on 2025-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_studentprofile_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم')], default='مبتدئ', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='monthly_level',
            field=models.CharField(blank=True, choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم')], max_length=20, null=True, verbose_name='التقييم الشهري'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='weekly_level',
            field=models.CharField(blank=True, choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم')], max_length=20, null=True, verbose_name='التقييم الأسبوعي'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='yearly_level',
            field=models.CharField(blank=True, choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم')], max_length=20, null=True, verbose_name='التقييم السنوي'),
        ),
    ]
