# Generated by Django 5.2.5 on 2025-08-27 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_studentprofile_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('review_rating', models.CharField(choices=[('ضعيف', 'ضعيف'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز'), ('ممتاز جدا', 'ممتاز جدا')], max_length=20)),
                ('memorization_rating', models.CharField(choices=[('ضعيف', 'ضعيف'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز'), ('ممتاز جدا', 'ممتاز جدا')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
