# Generated by Django 5.2.5 on 2025-08-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_weeklyprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyprogress',
            name='week_start',
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='day',
            field=models.CharField(choices=[('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الإثنين', 'الإثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], default='السبت', max_length=10),
        ),
    ]
