# Generated by Django 5.2.5 on 2025-08-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_weeklyprogress_week_start_weeklyprogress_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyprogress',
            unique_together={('student', 'day')},
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='memorized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyprogress',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='weeklyprogress',
            name='memorization_rating',
        ),
        migrations.RemoveField(
            model_name='weeklyprogress',
            name='review_rating',
        ),
    ]
