# Generated by Django 5.2.5 on 2025-08-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_weeklyprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='memorization_rating',
            field=models.CharField(blank=True, choices=[('ضعيف', 'ضعيف'), ('جيد', 'جيد'), ('جيد جدًا', 'جيد جدًا'), ('ممتاز', 'ممتاز'), ('ممتاز جدًا', 'ممتاز جدًا')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='review_rating',
            field=models.CharField(blank=True, choices=[('ضعيف', 'ضعيف'), ('جيد', 'جيد'), ('جيد جدًا', 'جيد جدًا'), ('ممتاز', 'ممتاز'), ('ممتاز جدًا', 'ممتاز جدًا')], max_length=20, null=True),
        ),
    ]
