# Generated by Django 5.2.5 on 2025-08-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_weeklyprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyprogress',
            name='memorized',
        ),
        migrations.RemoveField(
            model_name='weeklyprogress',
            name='reviews',
        ),
    ]
