# Generated by Django 5.2.5 on 2025-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_weeklyprogress_memorized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogress',
            name='day',
            field=models.CharField(choices=[('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الإثنين', 'الإثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], max_length=10),
        ),
    ]
