# Generated by Django 5.2.5 on 2025-08-31 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_weeklyprogress_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='shared_appointments', to=settings.AUTH_USER_MODEL, verbose_name='المشاركون'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=128, unique=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='users.lesson')),
            ],
        ),
    ]
