# Generated by Django 5.2.5 on 2025-08-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_appointment_participants_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='الحد الأقصى للمشاركين'),
        ),
    ]
