# Generated by Django 5.2.5 on 2025-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_appointment_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='موعد عام متاح للجميع'),
        ),
    ]
