# Generated by Django 5.2.5 on 2025-08-31 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_appointment_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='موعد عام (لأكثر من مشترك)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='appointments_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
