# Generated by Django 5.2.5 on 2025-08-31 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_appointment_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
