# Generated by Django 5.2.5 on 2025-08-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_appointment_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_code',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phase',
            field=models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('expert', 'متخصص'), ('general', 'المقراءه العامه')], default='beginner', max_length=20, verbose_name='المرحلة'),
        ),
    ]
