# Generated by Django 5.2.5 on 2025-08-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_plan_plan_code_alter_appointment_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_code',
            field=models.IntegerField(default=0),
        ),
    ]
