# Generated by Django 5.2.5 on 2025-09-04 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_plan_plan_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'المواعيد', 'verbose_name_plural': 'المواعيد'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'المستخدمين علي الموقع ', 'verbose_name_plural': 'المستخدمين علي الموقع '},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': 'التقييم العام ', 'verbose_name_plural': 'التقيمات العامه '},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'الدروس'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'لينك الاجتماع  ', 'verbose_name_plural': 'الاجتماعات'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'الرساله ', 'verbose_name_plural': 'الرسائل'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'الاشعارات ', 'verbose_name_plural': 'الاشعارات'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'فواتير الدفع', 'verbose_name_plural': 'فواتير الدفع'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'خطط الاشتراك ', 'verbose_name_plural': 'خطط الاشتراك '},
        ),
        migrations.AlterModelOptions(
            name='reviewplan',
            options={'verbose_name': 'خطط المراجعه للطالب ', 'verbose_name_plural': 'خطط المراجعه للطلاب '},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'معلومات  الطالب', 'verbose_name_plural': 'معلومات  الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'طلبات الاشتراك', 'verbose_name_plural': 'طلبات الاشتراك'},
        ),
        migrations.AlterModelOptions(
            name='weeklyprogress',
            options={'verbose_name': 'التقييم الأسبوعي', 'verbose_name_plural': 'التقيمات الأسبوعية'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_code',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الشخص الحاجز'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='موعد خاص'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='موعد عام '),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='group_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phase',
            field=models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('expert', 'متخصص'), ('general', 'المقرأة العامة')], default='beginner', max_length=20, verbose_name='المرحلة'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.plan', verbose_name='الخطة'),
        ),
    ]
