# Generated by Django 5.2.5 on 2025-09-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_appointment_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='custom_id',
            new_name='plan_code',
        ),
    ]
