# Generated by Django 5.2.5 on 2025-09-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_rename_custom_id_plan_plan_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_link', models.URLField(verbose_name='رابط الفورم')),
                ('spreadsheet_id', models.CharField(max_length=100, verbose_name='ID جدول جوجل')),
                ('range_name', models.CharField(default='Form Responses 1!A:D', max_length=50, verbose_name='نطاق الأعمدة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
