# Generated by Django 5.2.5 on 2025-09-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_googleformconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('score', models.CharField(max_length=50, verbose_name='النتيجة')),
                ('q1_answer', models.TextField(blank=True, null=True, verbose_name='إجابة السؤال 1')),
                ('q2_answer', models.TextField(blank=True, null=True, verbose_name='إجابة السؤال 2')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
            ],
        ),
        migrations.DeleteModel(
            name='GoogleFormConfig',
        ),
    ]
