# Generated by Django 5.2.5 on 2025-09-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_googleformresult_delete_googleformconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleformresult',
            name='q1_answer',
        ),
        migrations.RemoveField(
            model_name='googleformresult',
            name='q2_answer',
        ),
        migrations.AddField(
            model_name='googleformresult',
            name='answers',
            field=models.JSONField(blank=True, null=True, verbose_name='كل الإجابات'),
        ),
    ]
