# Generated by Django 5.2.5 on 2025-09-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_googleformresult_q1_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('google_form_link', models.URLField(verbose_name='رابط Google Form')),
                ('google_sheet_id', models.CharField(max_length=200, verbose_name='ID الـ Google Sheet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
