# Generated by Django 5.2.5 on 2025-09-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='google_sheet_id',
        ),
        migrations.AddField(
            model_name='exam',
            name='google_sheet_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط Google Sheet'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='google_form_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط Google Form'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الامتحان'),
        ),
    ]
