# Generated by Django 5.2.5 on 2025-09-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_exam_google_sheet_id_exam_google_sheet_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleformresult',
            name='form_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleformresult',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ'),
        ),
        migrations.AlterUniqueTogether(
            name='googleformresult',
            unique_together={('email', 'form_date', 'score')},
        ),
    ]
