# Generated by Django 5.2.5 on 2025-09-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_googleformresult_form_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='googleformresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='googleformresult',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='googleformresult',
            unique_together={('exam', 'email', 'form_date', 'score')},
        ),
    ]
