# Generated by Django 5.2.5 on 2025-09-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_googleformresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='stage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'مبتدئ'), (2, 'متوسط'), (3, 'متقدم'), (4, 'متخصص'), (7, 'المقرأة العامة')], null=True, verbose_name='المرحلة'),
        ),
    ]
