# Generated by Django 5.2.5 on 2025-09-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_exam_stage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='googleformresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='googleformresult',
            name='percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='النسبة المئوية'),
        ),
        migrations.AddConstraint(
            model_name='googleformresult',
            constraint=models.UniqueConstraint(fields=('exam', 'email', 'form_date', 'score'), name='unique_exam_result'),
        ),
    ]
