# Generated by Django 5.2.5 on 2025-09-06 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_googleformresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='users.exam'),
        ),
    ]
