# Generated by Django 5.2.5 on 2025-09-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_plan_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='exam',
        ),
        migrations.AddField(
            model_name='plan',
            name='stage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'مبتدئ'), (2, 'متوسط'), (3, 'متقدم'), (4, 'متخصص'), (7, 'المقرأة العامة')], null=True),
        ),
    ]
