# Generated by Django 5.2.5 on 2025-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_remove_plan_exam_plan_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'خطة اشتراك', 'verbose_name_plural': 'خطط الاشتراك'},
        ),
        migrations.AddField(
            model_name='plan',
            name='requires_exam',
            field=models.BooleanField(default=False, verbose_name='يحتاج امتحان؟'),
        ),
    ]
