# Generated by Django 5.2.5 on 2025-09-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_plan_options_plan_requires_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'خطط الاشتراك ', 'verbose_name_plural': 'خطط الاشتراك '},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='requires_exam',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stage',
        ),
        migrations.AddField(
            model_name='plan',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='users.exam'),
        ),
    ]
