# Generated by Django 5.2.5 on 2025-09-11 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_plan_options_remove_plan_requires_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإرسال')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('read', 'تم القراءة'), ('replied', 'تم الرد')], default='new', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المسؤول')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
    ]
