# Generated by Django 5.2.5 on 2025-09-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_contactmessage_options_contactmessage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.contactmessage'),
        ),
    ]
