# Generated by Django 5.2.5 on 2025-09-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_contactmessage_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'الرسائل الوارده ', 'verbose_name_plural': 'الرسائل الوارده '},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'الامتحانات ', 'verbose_name_plural': 'الامتحانات '},
        ),
        migrations.AlterModelOptions(
            name='googleformresult',
            options={'verbose_name': 'نتائج الامتحان ', 'verbose_name_plural': 'نتائج الامتحانات '},
        ),
        migrations.RemoveConstraint(
            model_name='googleformresult',
            name='unique_exam_result',
        ),
    ]
